quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/expense
quarkus.datasource.username=test
quarkus.datasource.password=test12345

quarkus.hibernate-orm.database.generation=update

mp.jwt.verify.issuer=expenses-app-v2
mp.jwt.publicKey.location=classpath:publicKey.pem
quarkus.smallrye-jwt.enabled=true