quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=test
quarkus.datasource.password=test12345
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true

mp.jwt.verify.issuer=expenses-api
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem

quarkus.http.auth.permission.authenticated.paths=/api/*
quarkus.http.auth.permission.authenticated.policy=authenticated

quarkus.http.auth.permission.auth.paths=/auth/*
quarkus.http.auth.permission.auth.policy=permit

quarkus.log.category."io.quarkus.security".level=DEBUG
quarkus.log.category."io.smallrye.jwt".level=DEBUG